// <auto-generated />
using System;
using AiCoachOs.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiCoachOs.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260919164358_AddProgramDesignerFoundation")]
    partial class AddProgramDesignerFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiCoachOs.Domain.AnatomyAndBiomechanics.AnatomicalRegion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("anatomical_regions", (string)null);
                });

            modelBuilder.Entity("AiCoachOs.Domain.AnatomyAndBiomechanics.BiomechanicalConsideration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Aspect")
                        .HasColumnType("integer")
                        .HasColumnName("aspect");

                    b.Property<int>("Certainty")
                        .HasColumnType("integer")
                        .HasColumnName("certainty");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("explanation");

                    b.Property<Guid?>("KnowledgeClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("knowledge_claim_id");

                    b.Property<string>("PracticalCues")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("practical_cues");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("summary");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Aspect");

                    b.HasIndex("Certainty");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("KnowledgeClaimId");

                    b.ToTable("biomechanical_considerations", (string)null);
                });

            modelBuilder.Entity("AiCoachOs.Domain.AnatomyAndBiomechanics.ExerciseJointAction", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<Guid>("JointActionId")
                        .HasColumnType("uuid")
                        .HasColumnName("joint_action_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("ExerciseId", "JointActionId");

                    b.HasIndex("JointActionId");

                    b.ToTable("exercise_joint_actions", (string)null);
                });

            modelBuilder.Entity("AiCoachOs.Domain.AnatomyAndBiomechanics.Joint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CommonName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("common_name");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("region_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("RegionId");

                    b.ToTable("joints", (string)null);
                });

            modelBuilder.Entity("AiCoachOs.Domain.AnatomyAndBiomechanics.JointAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer")
                        .HasColumnName("action_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("JointId")
                        .HasColumnType("uuid")
                        .HasColumnName("joint_id");

                    b.Property<int>("PlaneOfMotion")
                        .HasColumnType("integer")
                        .HasColumnName("plane_of_motion");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("JointId", "ActionType")
                        .IsUnique();

                    b.ToTable("joint_actions", (string)null);
                });

            modelBuilder.Entity("AiCoachOs.Domain.AnatomyAndBiomechanics.MuscleJointAction", b =>
                {
                    b.Property<Guid>("MuscleId")
                        .HasColumnType("uuid")
                        .HasColumnName("muscle_id");

                    b.Property<Guid>("JointActionId")
                        .HasColumnType("uuid")
                        .HasColumnName("joint_action_id");

                    b.Property<bool>("IsPrimaryAction")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary_action");

                    b.HasKey("MuscleId", "JointActionId");

                    b.HasIndex("JointActionId");

                    b.ToTable("muscle_joint_actions", (string)null);
                });

            modelBuilder.Entity("AiCoachOs.Domain.Clients.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("IntakeNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("AiCoachOs.Domain.Clients.ConsentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConsentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GrantedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsGranted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("consent_records", (string)null);
                });

            modelBuilder.Entity("AiCoachOs.Domain.Coaches.Coach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("IdentityUserId")
                        .IsUnique();

                    b.ToTable("coaches", (string)null);
                });

            modelBuilder.Entity("AiCoachOs.Domain.Exercises.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.ToTable("equipment", (string)null);
                });

            modelBuilder.Entity("AiCoachOs.Domain.Exercises.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Aliases")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("aliases");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("JointActions")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("joint_actions");

                    b.Property<int>("LocalFatigueCost")
                        .HasColumnType("integer")
                        .HasColumnName("local_fatigue_cost");

                    b.Property<int>("MetadataStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("metadata_status");

                    b.Property<Guid>("MovementPatternId")
                        .HasColumnType("uuid")
                        .HasColumnName("movement_pattern_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("ProgressionPotential")
                        .HasColumnType("integer")
                        .HasColumnName("progression_potential");

                    b.Property<int>("ResistanceProfile")
                        .HasColumnType("integer")
                        .HasColumnName("resistance_profile");

                    b.Property<int>("StabilityRequirement")
                        .HasColumnType("integer")
                        .HasColumnName("stability_requirement");

                    b.Property<int>("StimulusPotential")
                        .HasColumnType("integer")
                        .HasColumnName("stimulus_potential");

                    b.Property<Guid?>("SubstitutionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("substitution_group_id");

                    b.Property<int>("SystemicFatigueCost")
                        .HasColumnType("integer")
                        .HasColumnName("systemic_fatigue_cost");

                    b.Property<int>("TechnicalDemand")
                        .HasColumnType("integer")
                        .HasColumnName("technical_demand");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("MovementPatternId");

                    b.ToTable("exercises", (string)null);
                });

            modelBuilder.Entity("AiCoachOs.Domain.Exercises.ExerciseEquipment", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.HasKey("ExerciseId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("exercise_equipment", (string)null);
                });

            modelBuilder.Entity("AiCoachOs.Domain.Exercises.ExerciseMuscle", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<Guid>("MuscleId")
                        .HasColumnType("uuid")
                        .HasColumnName("muscle_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.HasKey("ExerciseId", "MuscleId");

                    b.HasIndex("MuscleId");

                    b.ToTable("exercise_muscles", (string)null);
                });

            modelBuilder.Entity("AiCoachOs.Domain.Exercises.ExerciseSubstitution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<string>("IntentPreservationNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("intent_preservation_notes");

                    b.Property<Guid>("SubstituteExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("substitute_exercise_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("SubstituteExerciseId");

                    b.ToTable("exercise_substitutions", (string)null);
                });

            modelBuilder.Entity("AiCoachOs.Domain.Exercises.MovementPattern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.ToTable("movement_patterns", (string)null);
                });

            modelBuilder.Entity("AiCoachOs.Domain.Exercises.Muscle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BodyPart")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("body_part");

                    b.Property<string>("CommonName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("common_name");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.ToTable("muscles", (string)null);
                });

            modelBuilder.Entity("AiCoachOs.Domain.Knowledge.KnowledgeClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClaimText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claim_text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("EvidenceLevel")
                        .HasColumnType("integer")
                        .HasColumnName("evidence_level");

                    b.Property<Guid?>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Limitations")
                        .HasColumnType("text")
                        .HasColumnName("limitations");

                    b.Property<string>("Population")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("population");

                    b.Property<string>("PracticalApplication")
                        .HasColumnType("text")
                        .HasColumnName("practical_application");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("question");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reviewed_by");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SupersededAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("superseded_at_utc");

                    b.Property<Guid?>("SupersededByClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("superseded_by_claim_id");

                    b.Property<string>("SupersessionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("supersession_reason");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("topic");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("Status");

                    b.HasIndex("SupersededByClaimId");

                    b.HasIndex("Topic");

                    b.ToTable("knowledge_claims", (string)null);
                });

            modelBuilder.Entity("AiCoachOs.Domain.Knowledge.KnowledgeClaimSource", b =>
                {
                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("RelevanceNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("relevance_note");

                    b.HasKey("ClaimId", "SourceId");

                    b.HasIndex("SourceId");

                    b.ToTable("knowledge_claim_sources", (string)null);
                });

            modelBuilder.Entity("AiCoachOs.Domain.Knowledge.KnowledgeSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Authors")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("authors");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Doi")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("doi");

                    b.Property<int>("EvidenceLevel")
                        .HasColumnType("integer")
                        .HasColumnName("evidence_level");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer")
                        .HasColumnName("source_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("url");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceLevel");

                    b.HasIndex("SourceType");

                    b.ToTable("knowledge_sources", (string)null);
                });

            modelBuilder.Entity("AiCoachOs.Domain.Programs.ExerciseSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CoachingNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("coaching_note");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EffortGuideline")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("effort_guideline");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int>("RestSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("rest_seconds");

                    b.Property<string>("SelectionRationale")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("selection_rationale");

                    b.Property<string>("TargetRepRange")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_rep_range");

                    b.Property<int>("TargetSets")
                        .HasColumnType("integer")
                        .HasColumnName("target_sets");

                    b.Property<Guid>("TrainingSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("training_session_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TrainingSessionId", "Order")
                        .IsUnique();

                    b.ToTable("exercise_slots", (string)null);
                });

            modelBuilder.Entity("AiCoachOs.Domain.Programs.Program", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("coach_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("RationaleSummary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("rationale_summary");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CoachId");

                    b.HasIndex("Status");

                    b.ToTable("programs", (string)null);
                });

            modelBuilder.Entity("AiCoachOs.Domain.Programs.ProgramMusclePriority", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Justification")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("justification");

                    b.Property<Guid>("MuscleId")
                        .HasColumnType("uuid")
                        .HasColumnName("muscle_id");

                    b.Property<int>("PriorityLevel")
                        .HasColumnType("integer")
                        .HasColumnName("priority_level");

                    b.Property<Guid>("ProgramVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_version_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("MuscleId");

                    b.HasIndex("ProgramVersionId", "MuscleId")
                        .IsUnique();

                    b.ToTable("program_muscle_priorities", (string)null);
                });

            modelBuilder.Entity("AiCoachOs.Domain.Programs.ProgramVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("change_reason");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<int>("RecoveryCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("recovery_capacity");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ProgramId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("program_versions", (string)null);
                });

            modelBuilder.Entity("AiCoachOs.Domain.Programs.TrainingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer")
                        .HasColumnName("day_number");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_duration_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("SessionIntent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("session_intent");

                    b.Property<Guid>("TrainingWeekId")
                        .HasColumnType("uuid")
                        .HasColumnName("training_week_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("TrainingWeekId", "DayNumber")
                        .IsUnique();

                    b.ToTable("training_sessions", (string)null);
                });

            modelBuilder.Entity("AiCoachOs.Domain.Programs.TrainingWeek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("ProgramVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_version_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer")
                        .HasColumnName("week_number");

                    b.HasKey("Id");

                    b.HasIndex("ProgramVersionId", "WeekNumber")
                        .IsUnique();

                    b.ToTable("training_weeks", (string)null);
                });

            modelBuilder.Entity("AiCoachOs.Domain.TrainingProfiles.ClientTrainingPriority", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FocusArea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("focus_area");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "Order");

                    b.ToTable("client_training_priorities", (string)null);
                });

            modelBuilder.Entity("AiCoachOs.Domain.TrainingProfiles.ClientTrainingProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExerciseConstraints")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("exercise_constraints");

                    b.Property<string>("ExercisePreferences")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("exercise_preferences");

                    b.Property<int>("ExperienceLevel")
                        .HasColumnType("integer")
                        .HasColumnName("experience_level");

                    b.Property<int?>("SessionDurationMaxMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("session_duration_max_minutes");

                    b.Property<int?>("SessionDurationMinMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("session_duration_min_minutes");

                    b.Property<int?>("SessionDurationTargetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("session_duration_target_minutes");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("_availableEquipmentIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("available_equipment_ids");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("client_training_profiles", (string)null);
                });

            modelBuilder.Entity("AiCoachOs.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AiCoachOs.Domain.AnatomyAndBiomechanics.BiomechanicalConsideration", b =>
                {
                    b.HasOne("AiCoachOs.Domain.Exercises.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiCoachOs.Domain.Knowledge.KnowledgeClaim", "KnowledgeClaim")
                        .WithMany()
                        .HasForeignKey("KnowledgeClaimId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Exercise");

                    b.Navigation("KnowledgeClaim");
                });

            modelBuilder.Entity("AiCoachOs.Domain.AnatomyAndBiomechanics.ExerciseJointAction", b =>
                {
                    b.HasOne("AiCoachOs.Domain.Exercises.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiCoachOs.Domain.AnatomyAndBiomechanics.JointAction", "JointAction")
                        .WithMany("Exercises")
                        .HasForeignKey("JointActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("JointAction");
                });

            modelBuilder.Entity("AiCoachOs.Domain.AnatomyAndBiomechanics.Joint", b =>
                {
                    b.HasOne("AiCoachOs.Domain.AnatomyAndBiomechanics.AnatomicalRegion", "Region")
                        .WithMany("Joints")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("AiCoachOs.Domain.AnatomyAndBiomechanics.JointAction", b =>
                {
                    b.HasOne("AiCoachOs.Domain.AnatomyAndBiomechanics.Joint", "Joint")
                        .WithMany("Actions")
                        .HasForeignKey("JointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Joint");
                });

            modelBuilder.Entity("AiCoachOs.Domain.AnatomyAndBiomechanics.MuscleJointAction", b =>
                {
                    b.HasOne("AiCoachOs.Domain.AnatomyAndBiomechanics.JointAction", "JointAction")
                        .WithMany("Muscles")
                        .HasForeignKey("JointActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiCoachOs.Domain.Exercises.Muscle", "Muscle")
                        .WithMany()
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JointAction");

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("AiCoachOs.Domain.Clients.Client", b =>
                {
                    b.OwnsOne("AiCoachOs.Domain.Clients.ClientGoal", "Goal", b1 =>
                        {
                            b1.Property<Guid>("ClientId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Notes")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("goal_notes");

                            b1.Property<string>("PrimaryGoal")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("goal_primary");

                            b1.Property<int?>("TargetTimelineWeeks")
                                .HasColumnType("integer")
                                .HasColumnName("goal_target_timeline_weeks");

                            b1.HasKey("ClientId");

                            b1.ToTable("clients");

                            b1.WithOwner()
                                .HasForeignKey("ClientId");
                        });

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("AiCoachOs.Domain.Exercises.Exercise", b =>
                {
                    b.HasOne("AiCoachOs.Domain.Exercises.MovementPattern", "MovementPattern")
                        .WithMany()
                        .HasForeignKey("MovementPatternId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MovementPattern");
                });

            modelBuilder.Entity("AiCoachOs.Domain.Exercises.ExerciseEquipment", b =>
                {
                    b.HasOne("AiCoachOs.Domain.Exercises.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiCoachOs.Domain.Exercises.Exercise", "Exercise")
                        .WithMany("Equipment")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("AiCoachOs.Domain.Exercises.ExerciseMuscle", b =>
                {
                    b.HasOne("AiCoachOs.Domain.Exercises.Exercise", "Exercise")
                        .WithMany("Muscles")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiCoachOs.Domain.Exercises.Muscle", "Muscle")
                        .WithMany()
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("AiCoachOs.Domain.Exercises.ExerciseSubstitution", b =>
                {
                    b.HasOne("AiCoachOs.Domain.Exercises.Exercise", "Exercise")
                        .WithMany("Substitutions")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiCoachOs.Domain.Exercises.Exercise", "SubstituteExercise")
                        .WithMany()
                        .HasForeignKey("SubstituteExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("SubstituteExercise");
                });

            modelBuilder.Entity("AiCoachOs.Domain.Knowledge.KnowledgeClaim", b =>
                {
                    b.HasOne("AiCoachOs.Domain.Exercises.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AiCoachOs.Domain.Knowledge.KnowledgeClaim", "SupersededByClaim")
                        .WithMany()
                        .HasForeignKey("SupersededByClaimId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Exercise");

                    b.Navigation("SupersededByClaim");
                });

            modelBuilder.Entity("AiCoachOs.Domain.Knowledge.KnowledgeClaimSource", b =>
                {
                    b.HasOne("AiCoachOs.Domain.Knowledge.KnowledgeClaim", "Claim")
                        .WithMany("Sources")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiCoachOs.Domain.Knowledge.KnowledgeSource", "Source")
                        .WithMany("ClaimSources")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("AiCoachOs.Domain.Programs.ExerciseSlot", b =>
                {
                    b.HasOne("AiCoachOs.Domain.Exercises.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiCoachOs.Domain.Programs.TrainingSession", "TrainingSession")
                        .WithMany("Slots")
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AiCoachOs.Domain.Programs.ProgressionRule", "ProgressionRule", b1 =>
                        {
                            b1.Property<Guid>("ExerciseSlotId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CurrentTarget")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("progression_target");

                            b1.Property<string>("IncrementCondition")
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)")
                                .HasColumnName("progression_condition");

                            b1.Property<string>("IncrementValue")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("progression_increment");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("progression_type");

                            b1.HasKey("ExerciseSlotId");

                            b1.ToTable("exercise_slots");

                            b1.WithOwner()
                                .HasForeignKey("ExerciseSlotId");
                        });

                    b.Navigation("Exercise");

                    b.Navigation("ProgressionRule");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("AiCoachOs.Domain.Programs.Program", b =>
                {
                    b.HasOne("AiCoachOs.Domain.Clients.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiCoachOs.Domain.Coaches.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AiCoachOs.Domain.Programs.GoalSnapshot", "GoalSnapshot", b1 =>
                        {
                            b1.Property<Guid>("ProgramId")
                                .HasColumnType("uuid");

                            b1.Property<string>("GoalEmphasis")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("goal_emphasis");

                            b1.Property<int>("PrimaryGoal")
                                .HasColumnType("integer")
                                .HasColumnName("goal_primary");

                            b1.Property<int?>("SecondaryGoal")
                                .HasColumnType("integer")
                                .HasColumnName("goal_secondary");

                            b1.Property<int?>("TargetTimelineWeeks")
                                .HasColumnType("integer")
                                .HasColumnName("goal_timeline_weeks");

                            b1.HasKey("ProgramId");

                            b1.ToTable("programs");

                            b1.WithOwner()
                                .HasForeignKey("ProgramId");
                        });

                    b.Navigation("Client");

                    b.Navigation("Coach");

                    b.Navigation("GoalSnapshot")
                        .IsRequired();
                });

            modelBuilder.Entity("AiCoachOs.Domain.Programs.ProgramMusclePriority", b =>
                {
                    b.HasOne("AiCoachOs.Domain.Exercises.Muscle", "Muscle")
                        .WithMany()
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiCoachOs.Domain.Programs.ProgramVersion", "ProgramVersion")
                        .WithMany("MusclePriorities")
                        .HasForeignKey("ProgramVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Muscle");

                    b.Navigation("ProgramVersion");
                });

            modelBuilder.Entity("AiCoachOs.Domain.Programs.ProgramVersion", b =>
                {
                    b.HasOne("AiCoachOs.Domain.Programs.Program", "Program")
                        .WithMany("Versions")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("AiCoachOs.Domain.Programs.TrainingSession", b =>
                {
                    b.HasOne("AiCoachOs.Domain.Programs.TrainingWeek", "TrainingWeek")
                        .WithMany("Sessions")
                        .HasForeignKey("TrainingWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingWeek");
                });

            modelBuilder.Entity("AiCoachOs.Domain.Programs.TrainingWeek", b =>
                {
                    b.HasOne("AiCoachOs.Domain.Programs.ProgramVersion", "ProgramVersion")
                        .WithMany("Weeks")
                        .HasForeignKey("ProgramVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramVersion");
                });

            modelBuilder.Entity("AiCoachOs.Domain.TrainingProfiles.ClientTrainingPriority", b =>
                {
                    b.HasOne("AiCoachOs.Domain.TrainingProfiles.ClientTrainingProfile", null)
                        .WithMany("Priorities")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiCoachOs.Domain.TrainingProfiles.ClientTrainingProfile", b =>
                {
                    b.OwnsOne("AiCoachOs.Domain.TrainingProfiles.TrainingAvailability", "WeeklyAvailability", b1 =>
                        {
                            b1.Property<Guid>("ClientTrainingProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AvailableDays")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("available_days");

                            b1.Property<string>("PreferredDays")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("preferred_days");

                            b1.Property<int>("SessionsPerWeek")
                                .HasColumnType("integer")
                                .HasColumnName("sessions_per_week");

                            b1.HasKey("ClientTrainingProfileId");

                            b1.ToTable("client_training_profiles");

                            b1.WithOwner()
                                .HasForeignKey("ClientTrainingProfileId");
                        });

                    b.Navigation("WeeklyAvailability")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AiCoachOs.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AiCoachOs.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiCoachOs.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AiCoachOs.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiCoachOs.Domain.AnatomyAndBiomechanics.AnatomicalRegion", b =>
                {
                    b.Navigation("Joints");
                });

            modelBuilder.Entity("AiCoachOs.Domain.AnatomyAndBiomechanics.Joint", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("AiCoachOs.Domain.AnatomyAndBiomechanics.JointAction", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("Muscles");
                });

            modelBuilder.Entity("AiCoachOs.Domain.Exercises.Exercise", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("Muscles");

                    b.Navigation("Substitutions");
                });

            modelBuilder.Entity("AiCoachOs.Domain.Knowledge.KnowledgeClaim", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("AiCoachOs.Domain.Knowledge.KnowledgeSource", b =>
                {
                    b.Navigation("ClaimSources");
                });

            modelBuilder.Entity("AiCoachOs.Domain.Programs.Program", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("AiCoachOs.Domain.Programs.ProgramVersion", b =>
                {
                    b.Navigation("MusclePriorities");

                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("AiCoachOs.Domain.Programs.TrainingSession", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("AiCoachOs.Domain.Programs.TrainingWeek", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("AiCoachOs.Domain.TrainingProfiles.ClientTrainingProfile", b =>
                {
                    b.Navigation("Priorities");
                });
#pragma warning restore 612, 618
        }
    }
}
